[package]
name = "blocking-mfrc522"
version = "0.2.1"
authors = ["filipton <filipton12@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Simple mfrc522 library"

[lib]

[dependencies]
embedded-hal = "1.0.0"
heapless = "0.8.0"

[features]
default = []
